#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Samuel Santos"
email = "sanmoo.cs@gmail.com"

[ui]
paginate = "auto"
pager = "delta"
default-command = "log"
diff-formatter = ":git"
